package net.azae.kata;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class ConvertTest {
	@Test 
	public void test_non_reg() {
		assertEquals(null, Convert.num2text("1.2"));
		assertEquals("un", Convert.num2text("1"));
		assertEquals("deux", Convert.num2text("2"));
		assertEquals("trois", Convert.num2text("3"));
		assertEquals("quatre", Convert.num2text("4"));
		assertEquals("cinq", Convert.num2text("5"));
		assertEquals("six", Convert.num2text("6"));
		assertEquals("sept", Convert.num2text("7"));
		assertEquals("huit", Convert.num2text("8"));
		assertEquals("neuf", Convert.num2text("9"));
		assertEquals("dix", Convert.num2text("10"));
		assertEquals("onze", Convert.num2text("11"));
		assertEquals("douze", Convert.num2text("12"));
		assertEquals("treize", Convert.num2text("13"));
		assertEquals("quatorze", Convert.num2text("14"));
		assertEquals("quinze", Convert.num2text("15"));
		assertEquals("seize", Convert.num2text("16"));
		assertEquals("dix sept", Convert.num2text("17"));
		assertEquals("dix huit", Convert.num2text("18"));
		assertEquals("dix neuf", Convert.num2text("19"));
		assertEquals("vingt", Convert.num2text("20"));
		assertEquals("vingt et un", Convert.num2text("21"));
		assertEquals("vingt deux", Convert.num2text("22"));
		assertEquals("vingt trois", Convert.num2text("23"));
		assertEquals("vingt quatre", Convert.num2text("24"));
		assertEquals("vingt cinq", Convert.num2text("25"));
		assertEquals("vingt six", Convert.num2text("26"));
		assertEquals("vingt sept", Convert.num2text("27"));
		assertEquals("vingt huit", Convert.num2text("28"));
		assertEquals("vingt neuf", Convert.num2text("29"));
		assertEquals("trente", Convert.num2text("30"));
		assertEquals("trente et un", Convert.num2text("31"));
		assertEquals("trente deux", Convert.num2text("32"));
		assertEquals("trente trois", Convert.num2text("33"));
		assertEquals("trente quatre", Convert.num2text("34"));
		assertEquals("trente cinq", Convert.num2text("35"));
		assertEquals("trente six", Convert.num2text("36"));
		assertEquals("trente sept", Convert.num2text("37"));
		assertEquals("trente huit", Convert.num2text("38"));
		assertEquals("trente neuf", Convert.num2text("39"));
		assertEquals("quarante", Convert.num2text("40"));
		assertEquals("quarante et un", Convert.num2text("41"));
		assertEquals("quarante deux", Convert.num2text("42"));
		assertEquals("quarante trois", Convert.num2text("43"));
		assertEquals("quarante quatre", Convert.num2text("44"));
		assertEquals("quarante cinq", Convert.num2text("45"));
		assertEquals("quarante six", Convert.num2text("46"));
		assertEquals("quarante sept", Convert.num2text("47"));
		assertEquals("quarante huit", Convert.num2text("48"));
		assertEquals("quarante neuf", Convert.num2text("49"));
		assertEquals("cinquante", Convert.num2text("50"));
		assertEquals("cinquante et un", Convert.num2text("51"));
		assertEquals("cinquante deux", Convert.num2text("52"));
		assertEquals("cinquante trois", Convert.num2text("53"));
		assertEquals("cinquante quatre", Convert.num2text("54"));
		assertEquals("cinquante cinq", Convert.num2text("55"));
		assertEquals("cinquante six", Convert.num2text("56"));
		assertEquals("cinquante sept", Convert.num2text("57"));
		assertEquals("cinquante huit", Convert.num2text("58"));
		assertEquals("cinquante neuf", Convert.num2text("59"));
		assertEquals("soixante", Convert.num2text("60"));
		assertEquals("soixante et un", Convert.num2text("61"));
		assertEquals("soixante deux", Convert.num2text("62"));
		assertEquals("soixante trois", Convert.num2text("63"));
		assertEquals("soixante quatre", Convert.num2text("64"));
		assertEquals("soixante cinq", Convert.num2text("65"));
		assertEquals("soixante six", Convert.num2text("66"));
		assertEquals("soixante sept", Convert.num2text("67"));
		assertEquals("soixante huit", Convert.num2text("68"));
		assertEquals("soixante neuf", Convert.num2text("69"));
		assertEquals("soixante dix", Convert.num2text("70"));
		assertEquals("soixante onze", Convert.num2text("71"));
		assertEquals("soixante douze", Convert.num2text("72"));
		assertEquals("soixante treize", Convert.num2text("73"));
		assertEquals("soixante quatorze", Convert.num2text("74"));
		assertEquals("soixante quinze", Convert.num2text("75"));
		assertEquals("soixante seize", Convert.num2text("76"));
		assertEquals("soixante dix sept", Convert.num2text("77"));
		assertEquals("soixante dix huit", Convert.num2text("78"));
		assertEquals("soixante dix neuf", Convert.num2text("79"));
		assertEquals("quatre vingt", Convert.num2text("80"));
		assertEquals("quatre vingt et un", Convert.num2text("81"));
		assertEquals("quatre vingt deux", Convert.num2text("82"));
		assertEquals("quatre vingt trois", Convert.num2text("83"));
		assertEquals("quatre vingt quatre", Convert.num2text("84"));
		assertEquals("quatre vingt cinq", Convert.num2text("85"));
		assertEquals("quatre vingt six", Convert.num2text("86"));
		assertEquals("quatre vingt sept", Convert.num2text("87"));
		assertEquals("quatre vingt huit", Convert.num2text("88"));
		assertEquals("quatre vingt neuf", Convert.num2text("89"));
		assertEquals("quatre vingt dix", Convert.num2text("90"));
		assertEquals("quatre vingt onze", Convert.num2text("91"));
		assertEquals("quatre vingt douze", Convert.num2text("92"));
		assertEquals("quatre vingt treize", Convert.num2text("93"));
		assertEquals("quatre vingt quatorze", Convert.num2text("94"));
		assertEquals("quatre vingt quinze", Convert.num2text("95"));
		assertEquals("quatre vingt seize", Convert.num2text("96"));
		assertEquals("quatre vingt dix sept", Convert.num2text("97"));
		assertEquals("quatre vingt dix huit", Convert.num2text("98"));
		assertEquals("quatre vingt dix neuf", Convert.num2text("99"));
		assertEquals("cent", Convert.num2text("100"));
		assertEquals("cent un", Convert.num2text("101"));
		assertEquals("cent deux", Convert.num2text("102"));
		assertEquals("cent trois", Convert.num2text("103"));
		assertEquals("cent quatre", Convert.num2text("104"));
		assertEquals("cent cinq", Convert.num2text("105"));
		assertEquals("cent six", Convert.num2text("106"));
		assertEquals("cent sept", Convert.num2text("107"));
		assertEquals("cent huit", Convert.num2text("108"));
		assertEquals("cent neuf", Convert.num2text("109"));
		assertEquals("cent dix", Convert.num2text("110"));
		assertEquals("cent onze", Convert.num2text("111"));
		assertEquals("cent douze", Convert.num2text("112"));
		assertEquals("cent treize", Convert.num2text("113"));
		assertEquals("cent quatorze", Convert.num2text("114"));
		assertEquals("cent quinze", Convert.num2text("115"));
		assertEquals("cent seize", Convert.num2text("116"));
		assertEquals("cent dix sept", Convert.num2text("117"));
		assertEquals("cent dix huit", Convert.num2text("118"));
		assertEquals("cent dix neuf", Convert.num2text("119"));
		assertEquals("cent vingt", Convert.num2text("120"));
		assertEquals("cent vingt et un", Convert.num2text("121"));
		assertEquals("cent vingt deux", Convert.num2text("122"));
		assertEquals("cent vingt trois", Convert.num2text("123"));
		assertEquals("cent vingt quatre", Convert.num2text("124"));
		assertEquals("cent vingt cinq", Convert.num2text("125"));
		assertEquals("cent vingt six", Convert.num2text("126"));
		assertEquals("cent vingt sept", Convert.num2text("127"));
		assertEquals("cent vingt huit", Convert.num2text("128"));
		assertEquals("cent vingt neuf", Convert.num2text("129"));
		assertEquals("cent trente", Convert.num2text("130"));
		assertEquals("cent trente et un", Convert.num2text("131"));
		assertEquals("cent trente deux", Convert.num2text("132"));
		assertEquals("cent trente trois", Convert.num2text("133"));
		assertEquals("cent trente quatre", Convert.num2text("134"));
		assertEquals("cent trente cinq", Convert.num2text("135"));
		assertEquals("cent trente six", Convert.num2text("136"));
		assertEquals("cent trente sept", Convert.num2text("137"));
		assertEquals("cent trente huit", Convert.num2text("138"));
		assertEquals("cent trente neuf", Convert.num2text("139"));
		assertEquals("cent quarante", Convert.num2text("140"));
		assertEquals("cent quarante et un", Convert.num2text("141"));
		assertEquals("cent quarante deux", Convert.num2text("142"));
		assertEquals("cent quarante trois", Convert.num2text("143"));
		assertEquals("cent quarante quatre", Convert.num2text("144"));
		assertEquals("cent quarante cinq", Convert.num2text("145"));
		assertEquals("cent quarante six", Convert.num2text("146"));
		assertEquals("cent quarante sept", Convert.num2text("147"));
		assertEquals("cent quarante huit", Convert.num2text("148"));
		assertEquals("cent quarante neuf", Convert.num2text("149"));
		assertEquals("cent cinquante", Convert.num2text("150"));
		assertEquals("cent cinquante et un", Convert.num2text("151"));
		assertEquals("cent cinquante deux", Convert.num2text("152"));
		assertEquals("cent cinquante trois", Convert.num2text("153"));
		assertEquals("cent cinquante quatre", Convert.num2text("154"));
		assertEquals("cent cinquante cinq", Convert.num2text("155"));
		assertEquals("cent cinquante six", Convert.num2text("156"));
		assertEquals("cent cinquante sept", Convert.num2text("157"));
		assertEquals("cent cinquante huit", Convert.num2text("158"));
		assertEquals("cent cinquante neuf", Convert.num2text("159"));
		assertEquals("cent soixante", Convert.num2text("160"));
		assertEquals("cent soixante et un", Convert.num2text("161"));
		assertEquals("cent soixante deux", Convert.num2text("162"));
		assertEquals("cent soixante trois", Convert.num2text("163"));
		assertEquals("cent soixante quatre", Convert.num2text("164"));
		assertEquals("cent soixante cinq", Convert.num2text("165"));
		assertEquals("cent soixante six", Convert.num2text("166"));
		assertEquals("cent soixante sept", Convert.num2text("167"));
		assertEquals("cent soixante huit", Convert.num2text("168"));
		assertEquals("cent soixante neuf", Convert.num2text("169"));
		assertEquals("cent soixante dix", Convert.num2text("170"));
		assertEquals("cent soixante onze", Convert.num2text("171"));
		assertEquals("cent soixante douze", Convert.num2text("172"));
		assertEquals("cent soixante treize", Convert.num2text("173"));
		assertEquals("cent soixante quatorze", Convert.num2text("174"));
		assertEquals("cent soixante quinze", Convert.num2text("175"));
		assertEquals("cent soixante seize", Convert.num2text("176"));
		assertEquals("cent soixante dix sept", Convert.num2text("177"));
		assertEquals("cent soixante dix huit", Convert.num2text("178"));
		assertEquals("cent soixante dix neuf", Convert.num2text("179"));
		assertEquals("cent quatre vingt", Convert.num2text("180"));
		assertEquals("cent quatre vingt et un", Convert.num2text("181"));
		assertEquals("cent quatre vingt deux", Convert.num2text("182"));
		assertEquals("cent quatre vingt trois", Convert.num2text("183"));
		assertEquals("cent quatre vingt quatre", Convert.num2text("184"));
		assertEquals("cent quatre vingt cinq", Convert.num2text("185"));
		assertEquals("cent quatre vingt six", Convert.num2text("186"));
		assertEquals("cent quatre vingt sept", Convert.num2text("187"));
		assertEquals("cent quatre vingt huit", Convert.num2text("188"));
		assertEquals("cent quatre vingt neuf", Convert.num2text("189"));
		assertEquals("cent quatre vingt dix", Convert.num2text("190"));
		assertEquals("cent quatre vingt onze", Convert.num2text("191"));
		assertEquals("cent quatre vingt douze", Convert.num2text("192"));
		assertEquals("cent quatre vingt treize", Convert.num2text("193"));
		assertEquals("cent quatre vingt quatorze", Convert.num2text("194"));
		assertEquals("cent quatre vingt quinze", Convert.num2text("195"));
		assertEquals("cent quatre vingt seize", Convert.num2text("196"));
		assertEquals("cent quatre vingt dix sept", Convert.num2text("197"));
		assertEquals("cent quatre vingt dix huit", Convert.num2text("198"));
		assertEquals("cent quatre vingt dix neuf", Convert.num2text("199"));
		assertEquals("deux cent", Convert.num2text("200"));
		assertEquals("deux cent un", Convert.num2text("201"));
		assertEquals("deux cent deux", Convert.num2text("202"));
		assertEquals("deux cent trois", Convert.num2text("203"));
		assertEquals("deux cent quatre", Convert.num2text("204"));
		assertEquals("deux cent cinq", Convert.num2text("205"));
		assertEquals("deux cent six", Convert.num2text("206"));
		assertEquals("deux cent sept", Convert.num2text("207"));
		assertEquals("deux cent huit", Convert.num2text("208"));
		assertEquals("deux cent neuf", Convert.num2text("209"));
		assertEquals("deux cent dix", Convert.num2text("210"));
		assertEquals("deux cent onze", Convert.num2text("211"));
		assertEquals("deux cent douze", Convert.num2text("212"));
		assertEquals("deux cent treize", Convert.num2text("213"));
		assertEquals("deux cent quatorze", Convert.num2text("214"));
		assertEquals("deux cent quinze", Convert.num2text("215"));
		assertEquals("deux cent seize", Convert.num2text("216"));
		assertEquals("deux cent dix sept", Convert.num2text("217"));
		assertEquals("deux cent dix huit", Convert.num2text("218"));
		assertEquals("deux cent dix neuf", Convert.num2text("219"));
		assertEquals("deux cent vingt", Convert.num2text("220"));
		assertEquals("deux cent vingt et un", Convert.num2text("221"));
		assertEquals("deux cent vingt deux", Convert.num2text("222"));
		assertEquals("deux cent vingt trois", Convert.num2text("223"));
		assertEquals("deux cent vingt quatre", Convert.num2text("224"));
		assertEquals("deux cent vingt cinq", Convert.num2text("225"));
		assertEquals("deux cent vingt six", Convert.num2text("226"));
		assertEquals("deux cent vingt sept", Convert.num2text("227"));
		assertEquals("deux cent vingt huit", Convert.num2text("228"));
		assertEquals("deux cent vingt neuf", Convert.num2text("229"));
		assertEquals("deux cent trente", Convert.num2text("230"));
		assertEquals("deux cent trente et un", Convert.num2text("231"));
		assertEquals("deux cent trente deux", Convert.num2text("232"));
		assertEquals("deux cent trente trois", Convert.num2text("233"));
		assertEquals("deux cent trente quatre", Convert.num2text("234"));
		assertEquals("deux cent trente cinq", Convert.num2text("235"));
		assertEquals("deux cent trente six", Convert.num2text("236"));
		assertEquals("deux cent trente sept", Convert.num2text("237"));
		assertEquals("deux cent trente huit", Convert.num2text("238"));
		assertEquals("deux cent trente neuf", Convert.num2text("239"));
		assertEquals("deux cent quarante", Convert.num2text("240"));
		assertEquals("deux cent quarante et un", Convert.num2text("241"));
		assertEquals("deux cent quarante deux", Convert.num2text("242"));
		assertEquals("deux cent quarante trois", Convert.num2text("243"));
		assertEquals("deux cent quarante quatre", Convert.num2text("244"));
		assertEquals("deux cent quarante cinq", Convert.num2text("245"));
		assertEquals("deux cent quarante six", Convert.num2text("246"));
		assertEquals("deux cent quarante sept", Convert.num2text("247"));
		assertEquals("deux cent quarante huit", Convert.num2text("248"));
		assertEquals("deux cent quarante neuf", Convert.num2text("249"));
		assertEquals("deux cent cinquante", Convert.num2text("250"));
		assertEquals("deux cent cinquante et un", Convert.num2text("251"));
		assertEquals("deux cent cinquante deux", Convert.num2text("252"));
		assertEquals("deux cent cinquante trois", Convert.num2text("253"));
		assertEquals("deux cent cinquante quatre", Convert.num2text("254"));
		assertEquals("deux cent cinquante cinq", Convert.num2text("255"));
		assertEquals("deux cent cinquante six", Convert.num2text("256"));
		assertEquals("deux cent cinquante sept", Convert.num2text("257"));
		assertEquals("deux cent cinquante huit", Convert.num2text("258"));
		assertEquals("deux cent cinquante neuf", Convert.num2text("259"));
		assertEquals("deux cent soixante", Convert.num2text("260"));
		assertEquals("deux cent soixante et un", Convert.num2text("261"));
		assertEquals("deux cent soixante deux", Convert.num2text("262"));
		assertEquals("deux cent soixante trois", Convert.num2text("263"));
		assertEquals("deux cent soixante quatre", Convert.num2text("264"));
		assertEquals("deux cent soixante cinq", Convert.num2text("265"));
		assertEquals("deux cent soixante six", Convert.num2text("266"));
		assertEquals("deux cent soixante sept", Convert.num2text("267"));
		assertEquals("deux cent soixante huit", Convert.num2text("268"));
		assertEquals("deux cent soixante neuf", Convert.num2text("269"));
		assertEquals("deux cent soixante dix", Convert.num2text("270"));
		assertEquals("deux cent soixante onze", Convert.num2text("271"));
		assertEquals("deux cent soixante douze", Convert.num2text("272"));
		assertEquals("deux cent soixante treize", Convert.num2text("273"));
		assertEquals("deux cent soixante quatorze", Convert.num2text("274"));
		assertEquals("deux cent soixante quinze", Convert.num2text("275"));
		assertEquals("deux cent soixante seize", Convert.num2text("276"));
		assertEquals("deux cent soixante dix sept", Convert.num2text("277"));
		assertEquals("deux cent soixante dix huit", Convert.num2text("278"));
		assertEquals("deux cent soixante dix neuf", Convert.num2text("279"));
		assertEquals("deux cent quatre vingt", Convert.num2text("280"));
		assertEquals("deux cent quatre vingt et un", Convert.num2text("281"));
		assertEquals("deux cent quatre vingt deux", Convert.num2text("282"));
		assertEquals("deux cent quatre vingt trois", Convert.num2text("283"));
		assertEquals("deux cent quatre vingt quatre", Convert.num2text("284"));
		assertEquals("deux cent quatre vingt cinq", Convert.num2text("285"));
		assertEquals("deux cent quatre vingt six", Convert.num2text("286"));
		assertEquals("deux cent quatre vingt sept", Convert.num2text("287"));
		assertEquals("deux cent quatre vingt huit", Convert.num2text("288"));
		assertEquals("deux cent quatre vingt neuf", Convert.num2text("289"));
		assertEquals("deux cent quatre vingt dix", Convert.num2text("290"));
		assertEquals("deux cent quatre vingt onze", Convert.num2text("291"));
		assertEquals("deux cent quatre vingt douze", Convert.num2text("292"));
		assertEquals("deux cent quatre vingt treize", Convert.num2text("293"));
		assertEquals("deux cent quatre vingt quatorze", Convert.num2text("294"));
		assertEquals("deux cent quatre vingt quinze", Convert.num2text("295"));
		assertEquals("deux cent quatre vingt seize", Convert.num2text("296"));
		assertEquals("deux cent quatre vingt dix sept", Convert.num2text("297"));
		assertEquals("deux cent quatre vingt dix huit", Convert.num2text("298"));
		assertEquals("deux cent quatre vingt dix neuf", Convert.num2text("299"));
		assertEquals("trois cent", Convert.num2text("300"));
		assertEquals("trois cent un", Convert.num2text("301"));
		assertEquals("trois cent deux", Convert.num2text("302"));
		assertEquals("trois cent trois", Convert.num2text("303"));
		assertEquals("trois cent quatre", Convert.num2text("304"));
		assertEquals("trois cent cinq", Convert.num2text("305"));
		assertEquals("trois cent six", Convert.num2text("306"));
		assertEquals("trois cent sept", Convert.num2text("307"));
		assertEquals("trois cent huit", Convert.num2text("308"));
		assertEquals("trois cent neuf", Convert.num2text("309"));
		assertEquals("trois cent dix", Convert.num2text("310"));
		assertEquals("trois cent onze", Convert.num2text("311"));
		assertEquals("trois cent douze", Convert.num2text("312"));
		assertEquals("trois cent treize", Convert.num2text("313"));
		assertEquals("trois cent quatorze", Convert.num2text("314"));
		assertEquals("trois cent quinze", Convert.num2text("315"));
		assertEquals("trois cent seize", Convert.num2text("316"));
		assertEquals("trois cent dix sept", Convert.num2text("317"));
		assertEquals("trois cent dix huit", Convert.num2text("318"));
		assertEquals("trois cent dix neuf", Convert.num2text("319"));
		assertEquals("trois cent vingt", Convert.num2text("320"));
		assertEquals("trois cent vingt et un", Convert.num2text("321"));
		assertEquals("trois cent vingt deux", Convert.num2text("322"));
		assertEquals("trois cent vingt trois", Convert.num2text("323"));
		assertEquals("trois cent vingt quatre", Convert.num2text("324"));
		assertEquals("trois cent vingt cinq", Convert.num2text("325"));
		assertEquals("trois cent vingt six", Convert.num2text("326"));
		assertEquals("trois cent vingt sept", Convert.num2text("327"));
		assertEquals("trois cent vingt huit", Convert.num2text("328"));
		assertEquals("trois cent vingt neuf", Convert.num2text("329"));
		assertEquals("trois cent trente", Convert.num2text("330"));
		assertEquals("trois cent trente et un", Convert.num2text("331"));
		assertEquals("trois cent trente deux", Convert.num2text("332"));
		assertEquals("trois cent trente trois", Convert.num2text("333"));
		assertEquals("trois cent trente quatre", Convert.num2text("334"));
		assertEquals("trois cent trente cinq", Convert.num2text("335"));
		assertEquals("trois cent trente six", Convert.num2text("336"));
		assertEquals("trois cent trente sept", Convert.num2text("337"));
		assertEquals("trois cent trente huit", Convert.num2text("338"));
		assertEquals("trois cent trente neuf", Convert.num2text("339"));
		assertEquals("trois cent quarante", Convert.num2text("340"));
		assertEquals("trois cent quarante et un", Convert.num2text("341"));
		assertEquals("trois cent quarante deux", Convert.num2text("342"));
		assertEquals("trois cent quarante trois", Convert.num2text("343"));
		assertEquals("trois cent quarante quatre", Convert.num2text("344"));
		assertEquals("trois cent quarante cinq", Convert.num2text("345"));
		assertEquals("trois cent quarante six", Convert.num2text("346"));
		assertEquals("trois cent quarante sept", Convert.num2text("347"));
		assertEquals("trois cent quarante huit", Convert.num2text("348"));
		assertEquals("trois cent quarante neuf", Convert.num2text("349"));
		assertEquals("trois cent cinquante", Convert.num2text("350"));
		assertEquals("trois cent cinquante et un", Convert.num2text("351"));
		assertEquals("trois cent cinquante deux", Convert.num2text("352"));
		assertEquals("trois cent cinquante trois", Convert.num2text("353"));
		assertEquals("trois cent cinquante quatre", Convert.num2text("354"));
		assertEquals("trois cent cinquante cinq", Convert.num2text("355"));
		assertEquals("trois cent cinquante six", Convert.num2text("356"));
		assertEquals("trois cent cinquante sept", Convert.num2text("357"));
		assertEquals("trois cent cinquante huit", Convert.num2text("358"));
		assertEquals("trois cent cinquante neuf", Convert.num2text("359"));
		assertEquals("trois cent soixante", Convert.num2text("360"));
		assertEquals("trois cent soixante et un", Convert.num2text("361"));
		assertEquals("trois cent soixante deux", Convert.num2text("362"));
		assertEquals("trois cent soixante trois", Convert.num2text("363"));
		assertEquals("trois cent soixante quatre", Convert.num2text("364"));
		assertEquals("trois cent soixante cinq", Convert.num2text("365"));
		assertEquals("trois cent soixante six", Convert.num2text("366"));
		assertEquals("trois cent soixante sept", Convert.num2text("367"));
		assertEquals("trois cent soixante huit", Convert.num2text("368"));
		assertEquals("trois cent soixante neuf", Convert.num2text("369"));
		assertEquals("trois cent soixante dix", Convert.num2text("370"));
		assertEquals("trois cent soixante onze", Convert.num2text("371"));
		assertEquals("trois cent soixante douze", Convert.num2text("372"));
		assertEquals("trois cent soixante treize", Convert.num2text("373"));
		assertEquals("trois cent soixante quatorze", Convert.num2text("374"));
		assertEquals("trois cent soixante quinze", Convert.num2text("375"));
		assertEquals("trois cent soixante seize", Convert.num2text("376"));
		assertEquals("trois cent soixante dix sept", Convert.num2text("377"));
		assertEquals("trois cent soixante dix huit", Convert.num2text("378"));
		assertEquals("trois cent soixante dix neuf", Convert.num2text("379"));
		assertEquals("trois cent quatre vingt", Convert.num2text("380"));
		assertEquals("trois cent quatre vingt et un", Convert.num2text("381"));
		assertEquals("trois cent quatre vingt deux", Convert.num2text("382"));
		assertEquals("trois cent quatre vingt trois", Convert.num2text("383"));
		assertEquals("trois cent quatre vingt quatre", Convert.num2text("384"));
		assertEquals("trois cent quatre vingt cinq", Convert.num2text("385"));
		assertEquals("trois cent quatre vingt six", Convert.num2text("386"));
		assertEquals("trois cent quatre vingt sept", Convert.num2text("387"));
		assertEquals("trois cent quatre vingt huit", Convert.num2text("388"));
		assertEquals("trois cent quatre vingt neuf", Convert.num2text("389"));
		assertEquals("trois cent quatre vingt dix", Convert.num2text("390"));
		assertEquals("trois cent quatre vingt onze", Convert.num2text("391"));
		assertEquals("trois cent quatre vingt douze", Convert.num2text("392"));
		assertEquals("trois cent quatre vingt treize", Convert.num2text("393"));
		assertEquals("trois cent quatre vingt quatorze", Convert.num2text("394"));
		assertEquals("trois cent quatre vingt quinze", Convert.num2text("395"));
		assertEquals("trois cent quatre vingt seize", Convert.num2text("396"));
		assertEquals("trois cent quatre vingt dix sept", Convert.num2text("397"));
		assertEquals("trois cent quatre vingt dix huit", Convert.num2text("398"));
		assertEquals("trois cent quatre vingt dix neuf", Convert.num2text("399"));
		assertEquals("quatre cent", Convert.num2text("400"));
		assertEquals("quatre cent un", Convert.num2text("401"));
		assertEquals("quatre cent deux", Convert.num2text("402"));
		assertEquals("quatre cent trois", Convert.num2text("403"));
		assertEquals("quatre cent quatre", Convert.num2text("404"));
		assertEquals("quatre cent cinq", Convert.num2text("405"));
		assertEquals("quatre cent six", Convert.num2text("406"));
		assertEquals("quatre cent sept", Convert.num2text("407"));
		assertEquals("quatre cent huit", Convert.num2text("408"));
		assertEquals("quatre cent neuf", Convert.num2text("409"));
		assertEquals("quatre cent dix", Convert.num2text("410"));
		assertEquals("quatre cent onze", Convert.num2text("411"));
		assertEquals("quatre cent douze", Convert.num2text("412"));
		assertEquals("quatre cent treize", Convert.num2text("413"));
		assertEquals("quatre cent quatorze", Convert.num2text("414"));
		assertEquals("quatre cent quinze", Convert.num2text("415"));
		assertEquals("quatre cent seize", Convert.num2text("416"));
		assertEquals("quatre cent dix sept", Convert.num2text("417"));
		assertEquals("quatre cent dix huit", Convert.num2text("418"));
		assertEquals("quatre cent dix neuf", Convert.num2text("419"));
		assertEquals("quatre cent vingt", Convert.num2text("420"));
		assertEquals("quatre cent vingt et un", Convert.num2text("421"));
		assertEquals("quatre cent vingt deux", Convert.num2text("422"));
		assertEquals("quatre cent vingt trois", Convert.num2text("423"));
		assertEquals("quatre cent vingt quatre", Convert.num2text("424"));
		assertEquals("quatre cent vingt cinq", Convert.num2text("425"));
		assertEquals("quatre cent vingt six", Convert.num2text("426"));
		assertEquals("quatre cent vingt sept", Convert.num2text("427"));
		assertEquals("quatre cent vingt huit", Convert.num2text("428"));
		assertEquals("quatre cent vingt neuf", Convert.num2text("429"));
		assertEquals("quatre cent trente", Convert.num2text("430"));
		assertEquals("quatre cent trente et un", Convert.num2text("431"));
		assertEquals("quatre cent trente deux", Convert.num2text("432"));
		assertEquals("quatre cent trente trois", Convert.num2text("433"));
		assertEquals("quatre cent trente quatre", Convert.num2text("434"));
		assertEquals("quatre cent trente cinq", Convert.num2text("435"));
		assertEquals("quatre cent trente six", Convert.num2text("436"));
		assertEquals("quatre cent trente sept", Convert.num2text("437"));
		assertEquals("quatre cent trente huit", Convert.num2text("438"));
		assertEquals("quatre cent trente neuf", Convert.num2text("439"));
		assertEquals("quatre cent quarante", Convert.num2text("440"));
		assertEquals("quatre cent quarante et un", Convert.num2text("441"));
		assertEquals("quatre cent quarante deux", Convert.num2text("442"));
		assertEquals("quatre cent quarante trois", Convert.num2text("443"));
		assertEquals("quatre cent quarante quatre", Convert.num2text("444"));
		assertEquals("quatre cent quarante cinq", Convert.num2text("445"));
		assertEquals("quatre cent quarante six", Convert.num2text("446"));
		assertEquals("quatre cent quarante sept", Convert.num2text("447"));
		assertEquals("quatre cent quarante huit", Convert.num2text("448"));
		assertEquals("quatre cent quarante neuf", Convert.num2text("449"));
		assertEquals("quatre cent cinquante", Convert.num2text("450"));
		assertEquals("quatre cent cinquante et un", Convert.num2text("451"));
		assertEquals("quatre cent cinquante deux", Convert.num2text("452"));
		assertEquals("quatre cent cinquante trois", Convert.num2text("453"));
		assertEquals("quatre cent cinquante quatre", Convert.num2text("454"));
		assertEquals("quatre cent cinquante cinq", Convert.num2text("455"));
		assertEquals("quatre cent cinquante six", Convert.num2text("456"));
		assertEquals("quatre cent cinquante sept", Convert.num2text("457"));
		assertEquals("quatre cent cinquante huit", Convert.num2text("458"));
		assertEquals("quatre cent cinquante neuf", Convert.num2text("459"));
		assertEquals("quatre cent soixante", Convert.num2text("460"));
		assertEquals("quatre cent soixante et un", Convert.num2text("461"));
		assertEquals("quatre cent soixante deux", Convert.num2text("462"));
		assertEquals("quatre cent soixante trois", Convert.num2text("463"));
		assertEquals("quatre cent soixante quatre", Convert.num2text("464"));
		assertEquals("quatre cent soixante cinq", Convert.num2text("465"));
		assertEquals("quatre cent soixante six", Convert.num2text("466"));
		assertEquals("quatre cent soixante sept", Convert.num2text("467"));
		assertEquals("quatre cent soixante huit", Convert.num2text("468"));
		assertEquals("quatre cent soixante neuf", Convert.num2text("469"));
		assertEquals("quatre cent soixante dix", Convert.num2text("470"));
		assertEquals("quatre cent soixante onze", Convert.num2text("471"));
		assertEquals("quatre cent soixante douze", Convert.num2text("472"));
		assertEquals("quatre cent soixante treize", Convert.num2text("473"));
		assertEquals("quatre cent soixante quatorze", Convert.num2text("474"));
		assertEquals("quatre cent soixante quinze", Convert.num2text("475"));
		assertEquals("quatre cent soixante seize", Convert.num2text("476"));
		assertEquals("quatre cent soixante dix sept", Convert.num2text("477"));
		assertEquals("quatre cent soixante dix huit", Convert.num2text("478"));
		assertEquals("quatre cent soixante dix neuf", Convert.num2text("479"));
		assertEquals("quatre cent quatre vingt", Convert.num2text("480"));
		assertEquals("quatre cent quatre vingt et un", Convert.num2text("481"));
		assertEquals("quatre cent quatre vingt deux", Convert.num2text("482"));
		assertEquals("quatre cent quatre vingt trois", Convert.num2text("483"));
		assertEquals("quatre cent quatre vingt quatre", Convert.num2text("484"));
		assertEquals("quatre cent quatre vingt cinq", Convert.num2text("485"));
		assertEquals("quatre cent quatre vingt six", Convert.num2text("486"));
		assertEquals("quatre cent quatre vingt sept", Convert.num2text("487"));
		assertEquals("quatre cent quatre vingt huit", Convert.num2text("488"));
		assertEquals("quatre cent quatre vingt neuf", Convert.num2text("489"));
		assertEquals("quatre cent quatre vingt dix", Convert.num2text("490"));
		assertEquals("quatre cent quatre vingt onze", Convert.num2text("491"));
		assertEquals("quatre cent quatre vingt douze", Convert.num2text("492"));
		assertEquals("quatre cent quatre vingt treize", Convert.num2text("493"));
		assertEquals("quatre cent quatre vingt quatorze", Convert.num2text("494"));
		assertEquals("quatre cent quatre vingt quinze", Convert.num2text("495"));
		assertEquals("quatre cent quatre vingt seize", Convert.num2text("496"));
		assertEquals("quatre cent quatre vingt dix sept", Convert.num2text("497"));
		assertEquals("quatre cent quatre vingt dix huit", Convert.num2text("498"));
		assertEquals("quatre cent quatre vingt dix neuf", Convert.num2text("499"));
		assertEquals("cinq cent", Convert.num2text("500"));
		assertEquals("cinq cent un", Convert.num2text("501"));
		assertEquals("cinq cent deux", Convert.num2text("502"));
		assertEquals("cinq cent trois", Convert.num2text("503"));
		assertEquals("cinq cent quatre", Convert.num2text("504"));
		assertEquals("cinq cent cinq", Convert.num2text("505"));
		assertEquals("cinq cent six", Convert.num2text("506"));
		assertEquals("cinq cent sept", Convert.num2text("507"));
		assertEquals("cinq cent huit", Convert.num2text("508"));
		assertEquals("cinq cent neuf", Convert.num2text("509"));
		assertEquals("cinq cent dix", Convert.num2text("510"));
		assertEquals("cinq cent onze", Convert.num2text("511"));
		assertEquals("cinq cent douze", Convert.num2text("512"));
		assertEquals("cinq cent treize", Convert.num2text("513"));
		assertEquals("cinq cent quatorze", Convert.num2text("514"));
		assertEquals("cinq cent quinze", Convert.num2text("515"));
		assertEquals("cinq cent seize", Convert.num2text("516"));
		assertEquals("cinq cent dix sept", Convert.num2text("517"));
		assertEquals("cinq cent dix huit", Convert.num2text("518"));
		assertEquals("cinq cent dix neuf", Convert.num2text("519"));
		assertEquals("cinq cent vingt", Convert.num2text("520"));
		assertEquals("cinq cent vingt et un", Convert.num2text("521"));
		assertEquals("cinq cent vingt deux", Convert.num2text("522"));
		assertEquals("cinq cent vingt trois", Convert.num2text("523"));
		assertEquals("cinq cent vingt quatre", Convert.num2text("524"));
		assertEquals("cinq cent vingt cinq", Convert.num2text("525"));
		assertEquals("cinq cent vingt six", Convert.num2text("526"));
		assertEquals("cinq cent vingt sept", Convert.num2text("527"));
		assertEquals("cinq cent vingt huit", Convert.num2text("528"));
		assertEquals("cinq cent vingt neuf", Convert.num2text("529"));
		assertEquals("cinq cent trente", Convert.num2text("530"));
		assertEquals("cinq cent trente et un", Convert.num2text("531"));
		assertEquals("cinq cent trente deux", Convert.num2text("532"));
		assertEquals("cinq cent trente trois", Convert.num2text("533"));
		assertEquals("cinq cent trente quatre", Convert.num2text("534"));
		assertEquals("cinq cent trente cinq", Convert.num2text("535"));
		assertEquals("cinq cent trente six", Convert.num2text("536"));
		assertEquals("cinq cent trente sept", Convert.num2text("537"));
		assertEquals("cinq cent trente huit", Convert.num2text("538"));
		assertEquals("cinq cent trente neuf", Convert.num2text("539"));
		assertEquals("cinq cent quarante", Convert.num2text("540"));
		assertEquals("cinq cent quarante et un", Convert.num2text("541"));
		assertEquals("cinq cent quarante deux", Convert.num2text("542"));
		assertEquals("cinq cent quarante trois", Convert.num2text("543"));
		assertEquals("cinq cent quarante quatre", Convert.num2text("544"));
		assertEquals("cinq cent quarante cinq", Convert.num2text("545"));
		assertEquals("cinq cent quarante six", Convert.num2text("546"));
		assertEquals("cinq cent quarante sept", Convert.num2text("547"));
		assertEquals("cinq cent quarante huit", Convert.num2text("548"));
		assertEquals("cinq cent quarante neuf", Convert.num2text("549"));
		assertEquals("cinq cent cinquante", Convert.num2text("550"));
		assertEquals("cinq cent cinquante et un", Convert.num2text("551"));
		assertEquals("cinq cent cinquante deux", Convert.num2text("552"));
		assertEquals("cinq cent cinquante trois", Convert.num2text("553"));
		assertEquals("cinq cent cinquante quatre", Convert.num2text("554"));
		assertEquals("cinq cent cinquante cinq", Convert.num2text("555"));
		assertEquals("cinq cent cinquante six", Convert.num2text("556"));
		assertEquals("cinq cent cinquante sept", Convert.num2text("557"));
		assertEquals("cinq cent cinquante huit", Convert.num2text("558"));
		assertEquals("cinq cent cinquante neuf", Convert.num2text("559"));
		assertEquals("cinq cent soixante", Convert.num2text("560"));
		assertEquals("cinq cent soixante et un", Convert.num2text("561"));
		assertEquals("cinq cent soixante deux", Convert.num2text("562"));
		assertEquals("cinq cent soixante trois", Convert.num2text("563"));
		assertEquals("cinq cent soixante quatre", Convert.num2text("564"));
		assertEquals("cinq cent soixante cinq", Convert.num2text("565"));
		assertEquals("cinq cent soixante six", Convert.num2text("566"));
		assertEquals("cinq cent soixante sept", Convert.num2text("567"));
		assertEquals("cinq cent soixante huit", Convert.num2text("568"));
		assertEquals("cinq cent soixante neuf", Convert.num2text("569"));
		assertEquals("cinq cent soixante dix", Convert.num2text("570"));
		assertEquals("cinq cent soixante onze", Convert.num2text("571"));
		assertEquals("cinq cent soixante douze", Convert.num2text("572"));
		assertEquals("cinq cent soixante treize", Convert.num2text("573"));
		assertEquals("cinq cent soixante quatorze", Convert.num2text("574"));
		assertEquals("cinq cent soixante quinze", Convert.num2text("575"));
		assertEquals("cinq cent soixante seize", Convert.num2text("576"));
		assertEquals("cinq cent soixante dix sept", Convert.num2text("577"));
		assertEquals("cinq cent soixante dix huit", Convert.num2text("578"));
		assertEquals("cinq cent soixante dix neuf", Convert.num2text("579"));
		assertEquals("cinq cent quatre vingt", Convert.num2text("580"));
		assertEquals("cinq cent quatre vingt et un", Convert.num2text("581"));
		assertEquals("cinq cent quatre vingt deux", Convert.num2text("582"));
		assertEquals("cinq cent quatre vingt trois", Convert.num2text("583"));
		assertEquals("cinq cent quatre vingt quatre", Convert.num2text("584"));
		assertEquals("cinq cent quatre vingt cinq", Convert.num2text("585"));
		assertEquals("cinq cent quatre vingt six", Convert.num2text("586"));
		assertEquals("cinq cent quatre vingt sept", Convert.num2text("587"));
		assertEquals("cinq cent quatre vingt huit", Convert.num2text("588"));
		assertEquals("cinq cent quatre vingt neuf", Convert.num2text("589"));
		assertEquals("cinq cent quatre vingt dix", Convert.num2text("590"));
		assertEquals("cinq cent quatre vingt onze", Convert.num2text("591"));
		assertEquals("cinq cent quatre vingt douze", Convert.num2text("592"));
		assertEquals("cinq cent quatre vingt treize", Convert.num2text("593"));
		assertEquals("cinq cent quatre vingt quatorze", Convert.num2text("594"));
		assertEquals("cinq cent quatre vingt quinze", Convert.num2text("595"));
		assertEquals("cinq cent quatre vingt seize", Convert.num2text("596"));
		assertEquals("cinq cent quatre vingt dix sept", Convert.num2text("597"));
		assertEquals("cinq cent quatre vingt dix huit", Convert.num2text("598"));
		assertEquals("cinq cent quatre vingt dix neuf", Convert.num2text("599"));
		assertEquals("six cent", Convert.num2text("600"));
		assertEquals("six cent un", Convert.num2text("601"));
		assertEquals("six cent deux", Convert.num2text("602"));
		assertEquals("six cent trois", Convert.num2text("603"));
		assertEquals("six cent quatre", Convert.num2text("604"));
		assertEquals("six cent cinq", Convert.num2text("605"));
		assertEquals("six cent six", Convert.num2text("606"));
		assertEquals("six cent sept", Convert.num2text("607"));
		assertEquals("six cent huit", Convert.num2text("608"));
		assertEquals("six cent neuf", Convert.num2text("609"));
		assertEquals("six cent dix", Convert.num2text("610"));
		assertEquals("six cent onze", Convert.num2text("611"));
		assertEquals("six cent douze", Convert.num2text("612"));
		assertEquals("six cent treize", Convert.num2text("613"));
		assertEquals("six cent quatorze", Convert.num2text("614"));
		assertEquals("six cent quinze", Convert.num2text("615"));
		assertEquals("six cent seize", Convert.num2text("616"));
		assertEquals("six cent dix sept", Convert.num2text("617"));
		assertEquals("six cent dix huit", Convert.num2text("618"));
		assertEquals("six cent dix neuf", Convert.num2text("619"));
		assertEquals("six cent vingt", Convert.num2text("620"));
		assertEquals("six cent vingt et un", Convert.num2text("621"));
		assertEquals("six cent vingt deux", Convert.num2text("622"));
		assertEquals("six cent vingt trois", Convert.num2text("623"));
		assertEquals("six cent vingt quatre", Convert.num2text("624"));
		assertEquals("six cent vingt cinq", Convert.num2text("625"));
		assertEquals("six cent vingt six", Convert.num2text("626"));
		assertEquals("six cent vingt sept", Convert.num2text("627"));
		assertEquals("six cent vingt huit", Convert.num2text("628"));
		assertEquals("six cent vingt neuf", Convert.num2text("629"));
		assertEquals("six cent trente", Convert.num2text("630"));
		assertEquals("six cent trente et un", Convert.num2text("631"));
		assertEquals("six cent trente deux", Convert.num2text("632"));
		assertEquals("six cent trente trois", Convert.num2text("633"));
		assertEquals("six cent trente quatre", Convert.num2text("634"));
		assertEquals("six cent trente cinq", Convert.num2text("635"));
		assertEquals("six cent trente six", Convert.num2text("636"));
		assertEquals("six cent trente sept", Convert.num2text("637"));
		assertEquals("six cent trente huit", Convert.num2text("638"));
		assertEquals("six cent trente neuf", Convert.num2text("639"));
		assertEquals("six cent quarante", Convert.num2text("640"));
		assertEquals("six cent quarante et un", Convert.num2text("641"));
		assertEquals("six cent quarante deux", Convert.num2text("642"));
		assertEquals("six cent quarante trois", Convert.num2text("643"));
		assertEquals("six cent quarante quatre", Convert.num2text("644"));
		assertEquals("six cent quarante cinq", Convert.num2text("645"));
		assertEquals("six cent quarante six", Convert.num2text("646"));
		assertEquals("six cent quarante sept", Convert.num2text("647"));
		assertEquals("six cent quarante huit", Convert.num2text("648"));
		assertEquals("six cent quarante neuf", Convert.num2text("649"));
		assertEquals("six cent cinquante", Convert.num2text("650"));
		assertEquals("six cent cinquante et un", Convert.num2text("651"));
		assertEquals("six cent cinquante deux", Convert.num2text("652"));
		assertEquals("six cent cinquante trois", Convert.num2text("653"));
		assertEquals("six cent cinquante quatre", Convert.num2text("654"));
		assertEquals("six cent cinquante cinq", Convert.num2text("655"));
		assertEquals("six cent cinquante six", Convert.num2text("656"));
		assertEquals("six cent cinquante sept", Convert.num2text("657"));
		assertEquals("six cent cinquante huit", Convert.num2text("658"));
		assertEquals("six cent cinquante neuf", Convert.num2text("659"));
		assertEquals("six cent soixante", Convert.num2text("660"));
		assertEquals("six cent soixante et un", Convert.num2text("661"));
		assertEquals("six cent soixante deux", Convert.num2text("662"));
		assertEquals("six cent soixante trois", Convert.num2text("663"));
		assertEquals("six cent soixante quatre", Convert.num2text("664"));
		assertEquals("six cent soixante cinq", Convert.num2text("665"));
		assertEquals("six cent soixante six", Convert.num2text("666"));
		assertEquals("six cent soixante sept", Convert.num2text("667"));
		assertEquals("six cent soixante huit", Convert.num2text("668"));
		assertEquals("six cent soixante neuf", Convert.num2text("669"));
		assertEquals("six cent soixante dix", Convert.num2text("670"));
		assertEquals("six cent soixante onze", Convert.num2text("671"));
		assertEquals("six cent soixante douze", Convert.num2text("672"));
		assertEquals("six cent soixante treize", Convert.num2text("673"));
		assertEquals("six cent soixante quatorze", Convert.num2text("674"));
		assertEquals("six cent soixante quinze", Convert.num2text("675"));
		assertEquals("six cent soixante seize", Convert.num2text("676"));
		assertEquals("six cent soixante dix sept", Convert.num2text("677"));
		assertEquals("six cent soixante dix huit", Convert.num2text("678"));
		assertEquals("six cent soixante dix neuf", Convert.num2text("679"));
		assertEquals("six cent quatre vingt", Convert.num2text("680"));
		assertEquals("six cent quatre vingt et un", Convert.num2text("681"));
		assertEquals("six cent quatre vingt deux", Convert.num2text("682"));
		assertEquals("six cent quatre vingt trois", Convert.num2text("683"));
		assertEquals("six cent quatre vingt quatre", Convert.num2text("684"));
		assertEquals("six cent quatre vingt cinq", Convert.num2text("685"));
		assertEquals("six cent quatre vingt six", Convert.num2text("686"));
		assertEquals("six cent quatre vingt sept", Convert.num2text("687"));
		assertEquals("six cent quatre vingt huit", Convert.num2text("688"));
		assertEquals("six cent quatre vingt neuf", Convert.num2text("689"));
		assertEquals("six cent quatre vingt dix", Convert.num2text("690"));
		assertEquals("six cent quatre vingt onze", Convert.num2text("691"));
		assertEquals("six cent quatre vingt douze", Convert.num2text("692"));
		assertEquals("six cent quatre vingt treize", Convert.num2text("693"));
		assertEquals("six cent quatre vingt quatorze", Convert.num2text("694"));
		assertEquals("six cent quatre vingt quinze", Convert.num2text("695"));
		assertEquals("six cent quatre vingt seize", Convert.num2text("696"));
		assertEquals("six cent quatre vingt dix sept", Convert.num2text("697"));
		assertEquals("six cent quatre vingt dix huit", Convert.num2text("698"));
		assertEquals("six cent quatre vingt dix neuf", Convert.num2text("699"));
		assertEquals("sept cent", Convert.num2text("700"));
		assertEquals("sept cent un", Convert.num2text("701"));
		assertEquals("sept cent deux", Convert.num2text("702"));
		assertEquals("sept cent trois", Convert.num2text("703"));
		assertEquals("sept cent quatre", Convert.num2text("704"));
		assertEquals("sept cent cinq", Convert.num2text("705"));
		assertEquals("sept cent six", Convert.num2text("706"));
		assertEquals("sept cent sept", Convert.num2text("707"));
		assertEquals("sept cent huit", Convert.num2text("708"));
		assertEquals("sept cent neuf", Convert.num2text("709"));
		assertEquals("sept cent dix", Convert.num2text("710"));
		assertEquals("sept cent onze", Convert.num2text("711"));
		assertEquals("sept cent douze", Convert.num2text("712"));
		assertEquals("sept cent treize", Convert.num2text("713"));
		assertEquals("sept cent quatorze", Convert.num2text("714"));
		assertEquals("sept cent quinze", Convert.num2text("715"));
		assertEquals("sept cent seize", Convert.num2text("716"));
		assertEquals("sept cent dix sept", Convert.num2text("717"));
		assertEquals("sept cent dix huit", Convert.num2text("718"));
		assertEquals("sept cent dix neuf", Convert.num2text("719"));
		assertEquals("sept cent vingt", Convert.num2text("720"));
		assertEquals("sept cent vingt et un", Convert.num2text("721"));
		assertEquals("sept cent vingt deux", Convert.num2text("722"));
		assertEquals("sept cent vingt trois", Convert.num2text("723"));
		assertEquals("sept cent vingt quatre", Convert.num2text("724"));
		assertEquals("sept cent vingt cinq", Convert.num2text("725"));
		assertEquals("sept cent vingt six", Convert.num2text("726"));
		assertEquals("sept cent vingt sept", Convert.num2text("727"));
		assertEquals("sept cent vingt huit", Convert.num2text("728"));
		assertEquals("sept cent vingt neuf", Convert.num2text("729"));
		assertEquals("sept cent trente", Convert.num2text("730"));
		assertEquals("sept cent trente et un", Convert.num2text("731"));
		assertEquals("sept cent trente deux", Convert.num2text("732"));
		assertEquals("sept cent trente trois", Convert.num2text("733"));
		assertEquals("sept cent trente quatre", Convert.num2text("734"));
		assertEquals("sept cent trente cinq", Convert.num2text("735"));
		assertEquals("sept cent trente six", Convert.num2text("736"));
		assertEquals("sept cent trente sept", Convert.num2text("737"));
		assertEquals("sept cent trente huit", Convert.num2text("738"));
		assertEquals("sept cent trente neuf", Convert.num2text("739"));
		assertEquals("sept cent quarante", Convert.num2text("740"));
		assertEquals("sept cent quarante et un", Convert.num2text("741"));
		assertEquals("sept cent quarante deux", Convert.num2text("742"));
		assertEquals("sept cent quarante trois", Convert.num2text("743"));
		assertEquals("sept cent quarante quatre", Convert.num2text("744"));
		assertEquals("sept cent quarante cinq", Convert.num2text("745"));
		assertEquals("sept cent quarante six", Convert.num2text("746"));
		assertEquals("sept cent quarante sept", Convert.num2text("747"));
		assertEquals("sept cent quarante huit", Convert.num2text("748"));
		assertEquals("sept cent quarante neuf", Convert.num2text("749"));
		assertEquals("sept cent cinquante", Convert.num2text("750"));
		assertEquals("sept cent cinquante et un", Convert.num2text("751"));
		assertEquals("sept cent cinquante deux", Convert.num2text("752"));
		assertEquals("sept cent cinquante trois", Convert.num2text("753"));
		assertEquals("sept cent cinquante quatre", Convert.num2text("754"));
		assertEquals("sept cent cinquante cinq", Convert.num2text("755"));
		assertEquals("sept cent cinquante six", Convert.num2text("756"));
		assertEquals("sept cent cinquante sept", Convert.num2text("757"));
		assertEquals("sept cent cinquante huit", Convert.num2text("758"));
		assertEquals("sept cent cinquante neuf", Convert.num2text("759"));
		assertEquals("sept cent soixante", Convert.num2text("760"));
		assertEquals("sept cent soixante et un", Convert.num2text("761"));
		assertEquals("sept cent soixante deux", Convert.num2text("762"));
		assertEquals("sept cent soixante trois", Convert.num2text("763"));
		assertEquals("sept cent soixante quatre", Convert.num2text("764"));
		assertEquals("sept cent soixante cinq", Convert.num2text("765"));
		assertEquals("sept cent soixante six", Convert.num2text("766"));
		assertEquals("sept cent soixante sept", Convert.num2text("767"));
		assertEquals("sept cent soixante huit", Convert.num2text("768"));
		assertEquals("sept cent soixante neuf", Convert.num2text("769"));
		assertEquals("sept cent soixante dix", Convert.num2text("770"));
		assertEquals("sept cent soixante onze", Convert.num2text("771"));
		assertEquals("sept cent soixante douze", Convert.num2text("772"));
		assertEquals("sept cent soixante treize", Convert.num2text("773"));
		assertEquals("sept cent soixante quatorze", Convert.num2text("774"));
		assertEquals("sept cent soixante quinze", Convert.num2text("775"));
		assertEquals("sept cent soixante seize", Convert.num2text("776"));
		assertEquals("sept cent soixante dix sept", Convert.num2text("777"));
		assertEquals("sept cent soixante dix huit", Convert.num2text("778"));
		assertEquals("sept cent soixante dix neuf", Convert.num2text("779"));
		assertEquals("sept cent quatre vingt", Convert.num2text("780"));
		assertEquals("sept cent quatre vingt et un", Convert.num2text("781"));
		assertEquals("sept cent quatre vingt deux", Convert.num2text("782"));
		assertEquals("sept cent quatre vingt trois", Convert.num2text("783"));
		assertEquals("sept cent quatre vingt quatre", Convert.num2text("784"));
		assertEquals("sept cent quatre vingt cinq", Convert.num2text("785"));
		assertEquals("sept cent quatre vingt six", Convert.num2text("786"));
		assertEquals("sept cent quatre vingt sept", Convert.num2text("787"));
		assertEquals("sept cent quatre vingt huit", Convert.num2text("788"));
		assertEquals("sept cent quatre vingt neuf", Convert.num2text("789"));
		assertEquals("sept cent quatre vingt dix", Convert.num2text("790"));
		assertEquals("sept cent quatre vingt onze", Convert.num2text("791"));
		assertEquals("sept cent quatre vingt douze", Convert.num2text("792"));
		assertEquals("sept cent quatre vingt treize", Convert.num2text("793"));
		assertEquals("sept cent quatre vingt quatorze", Convert.num2text("794"));
		assertEquals("sept cent quatre vingt quinze", Convert.num2text("795"));
		assertEquals("sept cent quatre vingt seize", Convert.num2text("796"));
		assertEquals("sept cent quatre vingt dix sept", Convert.num2text("797"));
		assertEquals("sept cent quatre vingt dix huit", Convert.num2text("798"));
		assertEquals("sept cent quatre vingt dix neuf", Convert.num2text("799"));
		assertEquals("huit cent", Convert.num2text("800"));
		assertEquals("huit cent un", Convert.num2text("801"));
		assertEquals("huit cent deux", Convert.num2text("802"));
		assertEquals("huit cent trois", Convert.num2text("803"));
		assertEquals("huit cent quatre", Convert.num2text("804"));
		assertEquals("huit cent cinq", Convert.num2text("805"));
		assertEquals("huit cent six", Convert.num2text("806"));
		assertEquals("huit cent sept", Convert.num2text("807"));
		assertEquals("huit cent huit", Convert.num2text("808"));
		assertEquals("huit cent neuf", Convert.num2text("809"));
		assertEquals("huit cent dix", Convert.num2text("810"));
		assertEquals("huit cent onze", Convert.num2text("811"));
		assertEquals("huit cent douze", Convert.num2text("812"));
		assertEquals("huit cent treize", Convert.num2text("813"));
		assertEquals("huit cent quatorze", Convert.num2text("814"));
		assertEquals("huit cent quinze", Convert.num2text("815"));
		assertEquals("huit cent seize", Convert.num2text("816"));
		assertEquals("huit cent dix sept", Convert.num2text("817"));
		assertEquals("huit cent dix huit", Convert.num2text("818"));
		assertEquals("huit cent dix neuf", Convert.num2text("819"));
		assertEquals("huit cent vingt", Convert.num2text("820"));
		assertEquals("huit cent vingt et un", Convert.num2text("821"));
		assertEquals("huit cent vingt deux", Convert.num2text("822"));
		assertEquals("huit cent vingt trois", Convert.num2text("823"));
		assertEquals("huit cent vingt quatre", Convert.num2text("824"));
		assertEquals("huit cent vingt cinq", Convert.num2text("825"));
		assertEquals("huit cent vingt six", Convert.num2text("826"));
		assertEquals("huit cent vingt sept", Convert.num2text("827"));
		assertEquals("huit cent vingt huit", Convert.num2text("828"));
		assertEquals("huit cent vingt neuf", Convert.num2text("829"));
		assertEquals("huit cent trente", Convert.num2text("830"));
		assertEquals("huit cent trente et un", Convert.num2text("831"));
		assertEquals("huit cent trente deux", Convert.num2text("832"));
		assertEquals("huit cent trente trois", Convert.num2text("833"));
		assertEquals("huit cent trente quatre", Convert.num2text("834"));
		assertEquals("huit cent trente cinq", Convert.num2text("835"));
		assertEquals("huit cent trente six", Convert.num2text("836"));
		assertEquals("huit cent trente sept", Convert.num2text("837"));
		assertEquals("huit cent trente huit", Convert.num2text("838"));
		assertEquals("huit cent trente neuf", Convert.num2text("839"));
		assertEquals("huit cent quarante", Convert.num2text("840"));
		assertEquals("huit cent quarante et un", Convert.num2text("841"));
		assertEquals("huit cent quarante deux", Convert.num2text("842"));
		assertEquals("huit cent quarante trois", Convert.num2text("843"));
		assertEquals("huit cent quarante quatre", Convert.num2text("844"));
		assertEquals("huit cent quarante cinq", Convert.num2text("845"));
		assertEquals("huit cent quarante six", Convert.num2text("846"));
		assertEquals("huit cent quarante sept", Convert.num2text("847"));
		assertEquals("huit cent quarante huit", Convert.num2text("848"));
		assertEquals("huit cent quarante neuf", Convert.num2text("849"));
		assertEquals("huit cent cinquante", Convert.num2text("850"));
		assertEquals("huit cent cinquante et un", Convert.num2text("851"));
		assertEquals("huit cent cinquante deux", Convert.num2text("852"));
		assertEquals("huit cent cinquante trois", Convert.num2text("853"));
		assertEquals("huit cent cinquante quatre", Convert.num2text("854"));
		assertEquals("huit cent cinquante cinq", Convert.num2text("855"));
		assertEquals("huit cent cinquante six", Convert.num2text("856"));
		assertEquals("huit cent cinquante sept", Convert.num2text("857"));
		assertEquals("huit cent cinquante huit", Convert.num2text("858"));
		assertEquals("huit cent cinquante neuf", Convert.num2text("859"));
		assertEquals("huit cent soixante", Convert.num2text("860"));
		assertEquals("huit cent soixante et un", Convert.num2text("861"));
		assertEquals("huit cent soixante deux", Convert.num2text("862"));
		assertEquals("huit cent soixante trois", Convert.num2text("863"));
		assertEquals("huit cent soixante quatre", Convert.num2text("864"));
		assertEquals("huit cent soixante cinq", Convert.num2text("865"));
		assertEquals("huit cent soixante six", Convert.num2text("866"));
		assertEquals("huit cent soixante sept", Convert.num2text("867"));
		assertEquals("huit cent soixante huit", Convert.num2text("868"));
		assertEquals("huit cent soixante neuf", Convert.num2text("869"));
		assertEquals("huit cent soixante dix", Convert.num2text("870"));
		assertEquals("huit cent soixante onze", Convert.num2text("871"));
		assertEquals("huit cent soixante douze", Convert.num2text("872"));
		assertEquals("huit cent soixante treize", Convert.num2text("873"));
		assertEquals("huit cent soixante quatorze", Convert.num2text("874"));
		assertEquals("huit cent soixante quinze", Convert.num2text("875"));
		assertEquals("huit cent soixante seize", Convert.num2text("876"));
		assertEquals("huit cent soixante dix sept", Convert.num2text("877"));
		assertEquals("huit cent soixante dix huit", Convert.num2text("878"));
		assertEquals("huit cent soixante dix neuf", Convert.num2text("879"));
		assertEquals("huit cent quatre vingt", Convert.num2text("880"));
		assertEquals("huit cent quatre vingt et un", Convert.num2text("881"));
		assertEquals("huit cent quatre vingt deux", Convert.num2text("882"));
		assertEquals("huit cent quatre vingt trois", Convert.num2text("883"));
		assertEquals("huit cent quatre vingt quatre", Convert.num2text("884"));
		assertEquals("huit cent quatre vingt cinq", Convert.num2text("885"));
		assertEquals("huit cent quatre vingt six", Convert.num2text("886"));
		assertEquals("huit cent quatre vingt sept", Convert.num2text("887"));
		assertEquals("huit cent quatre vingt huit", Convert.num2text("888"));
		assertEquals("huit cent quatre vingt neuf", Convert.num2text("889"));
		assertEquals("huit cent quatre vingt dix", Convert.num2text("890"));
		assertEquals("huit cent quatre vingt onze", Convert.num2text("891"));
		assertEquals("huit cent quatre vingt douze", Convert.num2text("892"));
		assertEquals("huit cent quatre vingt treize", Convert.num2text("893"));
		assertEquals("huit cent quatre vingt quatorze", Convert.num2text("894"));
		assertEquals("huit cent quatre vingt quinze", Convert.num2text("895"));
		assertEquals("huit cent quatre vingt seize", Convert.num2text("896"));
		assertEquals("huit cent quatre vingt dix sept", Convert.num2text("897"));
		assertEquals("huit cent quatre vingt dix huit", Convert.num2text("898"));
		assertEquals("huit cent quatre vingt dix neuf", Convert.num2text("899"));
		assertEquals("neuf cent", Convert.num2text("900"));
		assertEquals("neuf cent un", Convert.num2text("901"));
		assertEquals("neuf cent deux", Convert.num2text("902"));
		assertEquals("neuf cent trois", Convert.num2text("903"));
		assertEquals("neuf cent quatre", Convert.num2text("904"));
		assertEquals("neuf cent cinq", Convert.num2text("905"));
		assertEquals("neuf cent six", Convert.num2text("906"));
		assertEquals("neuf cent sept", Convert.num2text("907"));
		assertEquals("neuf cent huit", Convert.num2text("908"));
		assertEquals("neuf cent neuf", Convert.num2text("909"));
		assertEquals("neuf cent dix", Convert.num2text("910"));
		assertEquals("neuf cent onze", Convert.num2text("911"));
		assertEquals("neuf cent douze", Convert.num2text("912"));
		assertEquals("neuf cent treize", Convert.num2text("913"));
		assertEquals("neuf cent quatorze", Convert.num2text("914"));
		assertEquals("neuf cent quinze", Convert.num2text("915"));
		assertEquals("neuf cent seize", Convert.num2text("916"));
		assertEquals("neuf cent dix sept", Convert.num2text("917"));
		assertEquals("neuf cent dix huit", Convert.num2text("918"));
		assertEquals("neuf cent dix neuf", Convert.num2text("919"));
		assertEquals("neuf cent vingt", Convert.num2text("920"));
		assertEquals("neuf cent vingt et un", Convert.num2text("921"));
		assertEquals("neuf cent vingt deux", Convert.num2text("922"));
		assertEquals("neuf cent vingt trois", Convert.num2text("923"));
		assertEquals("neuf cent vingt quatre", Convert.num2text("924"));
		assertEquals("neuf cent vingt cinq", Convert.num2text("925"));
		assertEquals("neuf cent vingt six", Convert.num2text("926"));
		assertEquals("neuf cent vingt sept", Convert.num2text("927"));
		assertEquals("neuf cent vingt huit", Convert.num2text("928"));
		assertEquals("neuf cent vingt neuf", Convert.num2text("929"));
		assertEquals("neuf cent trente", Convert.num2text("930"));
		assertEquals("neuf cent trente et un", Convert.num2text("931"));
		assertEquals("neuf cent trente deux", Convert.num2text("932"));
		assertEquals("neuf cent trente trois", Convert.num2text("933"));
		assertEquals("neuf cent trente quatre", Convert.num2text("934"));
		assertEquals("neuf cent trente cinq", Convert.num2text("935"));
		assertEquals("neuf cent trente six", Convert.num2text("936"));
		assertEquals("neuf cent trente sept", Convert.num2text("937"));
		assertEquals("neuf cent trente huit", Convert.num2text("938"));
		assertEquals("neuf cent trente neuf", Convert.num2text("939"));
		assertEquals("neuf cent quarante", Convert.num2text("940"));
		assertEquals("neuf cent quarante et un", Convert.num2text("941"));
		assertEquals("neuf cent quarante deux", Convert.num2text("942"));
		assertEquals("neuf cent quarante trois", Convert.num2text("943"));
		assertEquals("neuf cent quarante quatre", Convert.num2text("944"));
		assertEquals("neuf cent quarante cinq", Convert.num2text("945"));
		assertEquals("neuf cent quarante six", Convert.num2text("946"));
		assertEquals("neuf cent quarante sept", Convert.num2text("947"));
		assertEquals("neuf cent quarante huit", Convert.num2text("948"));
		assertEquals("neuf cent quarante neuf", Convert.num2text("949"));
		assertEquals("neuf cent cinquante", Convert.num2text("950"));
		assertEquals("neuf cent cinquante et un", Convert.num2text("951"));
		assertEquals("neuf cent cinquante deux", Convert.num2text("952"));
		assertEquals("neuf cent cinquante trois", Convert.num2text("953"));
		assertEquals("neuf cent cinquante quatre", Convert.num2text("954"));
		assertEquals("neuf cent cinquante cinq", Convert.num2text("955"));
		assertEquals("neuf cent cinquante six", Convert.num2text("956"));
		assertEquals("neuf cent cinquante sept", Convert.num2text("957"));
		assertEquals("neuf cent cinquante huit", Convert.num2text("958"));
		assertEquals("neuf cent cinquante neuf", Convert.num2text("959"));
		assertEquals("neuf cent soixante", Convert.num2text("960"));
		assertEquals("neuf cent soixante et un", Convert.num2text("961"));
		assertEquals("neuf cent soixante deux", Convert.num2text("962"));
		assertEquals("neuf cent soixante trois", Convert.num2text("963"));
		assertEquals("neuf cent soixante quatre", Convert.num2text("964"));
		assertEquals("neuf cent soixante cinq", Convert.num2text("965"));
		assertEquals("neuf cent soixante six", Convert.num2text("966"));
		assertEquals("neuf cent soixante sept", Convert.num2text("967"));
		assertEquals("neuf cent soixante huit", Convert.num2text("968"));
		assertEquals("neuf cent soixante neuf", Convert.num2text("969"));
		assertEquals("neuf cent soixante dix", Convert.num2text("970"));
		assertEquals("neuf cent soixante onze", Convert.num2text("971"));
		assertEquals("neuf cent soixante douze", Convert.num2text("972"));
		assertEquals("neuf cent soixante treize", Convert.num2text("973"));
		assertEquals("neuf cent soixante quatorze", Convert.num2text("974"));
		assertEquals("neuf cent soixante quinze", Convert.num2text("975"));
		assertEquals("neuf cent soixante seize", Convert.num2text("976"));
		assertEquals("neuf cent soixante dix sept", Convert.num2text("977"));
		assertEquals("neuf cent soixante dix huit", Convert.num2text("978"));
		assertEquals("neuf cent soixante dix neuf", Convert.num2text("979"));
		assertEquals("neuf cent quatre vingt", Convert.num2text("980"));
		assertEquals("neuf cent quatre vingt et un", Convert.num2text("981"));
		assertEquals("neuf cent quatre vingt deux", Convert.num2text("982"));
		assertEquals("neuf cent quatre vingt trois", Convert.num2text("983"));
		assertEquals("neuf cent quatre vingt quatre", Convert.num2text("984"));
		assertEquals("neuf cent quatre vingt cinq", Convert.num2text("985"));
		assertEquals("neuf cent quatre vingt six", Convert.num2text("986"));
		assertEquals("neuf cent quatre vingt sept", Convert.num2text("987"));
		assertEquals("neuf cent quatre vingt huit", Convert.num2text("988"));
		assertEquals("neuf cent quatre vingt neuf", Convert.num2text("989"));
		assertEquals("neuf cent quatre vingt dix", Convert.num2text("990"));
		assertEquals("neuf cent quatre vingt onze", Convert.num2text("991"));
		assertEquals("neuf cent quatre vingt douze", Convert.num2text("992"));
		assertEquals("neuf cent quatre vingt treize", Convert.num2text("993"));
		assertEquals("neuf cent quatre vingt quatorze", Convert.num2text("994"));
		assertEquals("neuf cent quatre vingt quinze", Convert.num2text("995"));
		assertEquals("neuf cent quatre vingt seize", Convert.num2text("996"));
		assertEquals("neuf cent quatre vingt dix sept", Convert.num2text("997"));
		assertEquals("neuf cent quatre vingt dix huit", Convert.num2text("998"));
		assertEquals("neuf cent quatre vingt dix neuf", Convert.num2text("999"));
		assertEquals("mille", Convert.num2text("1000"));
		assertEquals("mille un", Convert.num2text("1001"));
		assertEquals("mille deux", Convert.num2text("1002"));
		assertEquals("mille trois", Convert.num2text("1003"));
		assertEquals("dix mille soixante dix huit", Convert.num2text("10078"));
		assertEquals("deux million sept mille huit", Convert.num2text("2007008"));
		assertEquals("million sept mille huit", Convert.num2text("1007008"));
		assertEquals("quatre milliard sept cent mille huit", Convert.num2text("4000700008"));
		assertEquals("neuf billion sept cent mille huit", Convert.num2text("9000000700008"));
		assertEquals("neuf billiar douze billion trois cent milliard sept cent mille huit", Convert.num2text("9012300000700008"));
	}
}
